# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'master.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 839)
        MainWindow.setStyleSheet("#page_1, #page_2\n"
"{\n"
"    border-image:url(:/newPrefix/11.jpg)0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"#page_3, #page_4, #page_5, #page\n"
"{\n"
"    background-color: rgb(254, 247, 230, 0.5);\n"
"}\n"
"#frame\n"
"{\n"
"    background-color: rgb(250, 255, 239, 0.8);\n"
"}\n"
"#frame_login\n"
"{\n"
"    background-color: rgb(255, 251, 228, 0.7);\n"
"}\n"
"#pushButton_mainIcon\n"
"{\n"
"background-color:rgb(104, 92, 85);\n"
"border: none;\n"
"}\n"
"\n"
"#pushButton_forgetPassword\n"
"{\n"
"    background:none;\n"
"border:none;\n"
"font-size: 25px\n"
"}\n"
"\n"
"#pushButton_forgetPassword:hover\n"
"{\n"
"    background-color:rgb(224, 234, 194);\n"
"}\n"
"\n"
"#pushButton_password, #pushButton_username\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"\n"
"#pushButton_login\n"
"{\n"
"    background-color:rgb(254, 255, 248);\n"
"font-size: 25px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"#lineEdit_username, #lineEdit_password\n"
"{\n"
"font-size: 25px\n"
"}\n"
"\n"
"#label__showImage_3\n"
"{\n"
"border: 3px outset;\n"
"border-color: rgb(102, 69, 45);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setMinimumSize(QtCore.QSize(250, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_videoSearchP = QtWidgets.QPushButton(self.frame)
        self.pushButton_videoSearchP.setMinimumSize(QtCore.QSize(50, 60))
        self.pushButton_videoSearchP.setStyleSheet("background-color: rgb(120, 90, 80);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(8, 8, 8);\n"
"border-style: outset;\n"
"border-radius:15px;\n"
"border-width:1.5px;\n"
"font: bold italic 15pt \"MS Sans Serif\";")
        self.pushButton_videoSearchP.setObjectName("pushButton_videoSearchP")
        self.verticalLayout_3.addWidget(self.pushButton_videoSearchP)
        self.pushButton_imageSearchP = QtWidgets.QPushButton(self.frame)
        self.pushButton_imageSearchP.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_imageSearchP.setStyleSheet("background-color: rgb(120, 90, 80);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(8, 8, 8);\n"
"border-style: outset;\n"
"border-radius:15px;\n"
"border-width:1.5px;\n"
"font: bold italic 15pt \"MS Sans Serif\";")
        self.pushButton_imageSearchP.setObjectName("pushButton_imageSearchP")
        self.verticalLayout_3.addWidget(self.pushButton_imageSearchP)
        self.pushButton_videoUploadP = QtWidgets.QPushButton(self.frame)
        self.pushButton_videoUploadP.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_videoUploadP.setStyleSheet("background-color: rgb(120, 90, 80);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(8, 8, 8);\n"
"border-style: outset;\n"
"border-radius:15px;\n"
"border-width:1.5px;\n"
"font: bold italic 15pt \"MS Sans Serif\";")
        self.pushButton_videoUploadP.setObjectName("pushButton_videoUploadP")
        self.verticalLayout_3.addWidget(self.pushButton_videoUploadP)
        self.pushButton_imageUploadP = QtWidgets.QPushButton(self.frame)
        self.pushButton_imageUploadP.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_imageUploadP.setStyleSheet("background-color: rgb(120, 90, 80);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(8, 8, 8);\n"
"border-style: outset;\n"
"border-radius:15px;\n"
"border-width:1.5px;\n"
"font: bold italic 15pt \"MS Sans Serif\";")
        self.pushButton_imageUploadP.setObjectName("pushButton_imageUploadP")
        self.verticalLayout_3.addWidget(self.pushButton_imageUploadP)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setStyleSheet("color: rgb(120, 90, 80);\n"
"background-color: rgb(245, 249, 237);\n"
"font: bold 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(8, 8, 8);")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton.setStyleSheet("color: rgb(120, 90, 80);\n"
"background-color: rgb(245, 249, 237);\n"
"font: bold 10pt \"MS Shell Dlg 2\";\n"
"\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(8, 8, 8);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label__showImage = QtWidgets.QLabel(self.page)
        self.label__showImage.setMinimumSize(QtCore.QSize(500, 250))
        self.label__showImage.setMaximumSize(QtCore.QSize(500, 300))
        self.label__showImage.setText("")
        self.label__showImage.setScaledContents(True)
        self.label__showImage.setObjectName("label__showImage")
        self.horizontalLayout_3.addWidget(self.label__showImage)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_imageHistogramSearch = QtWidgets.QPushButton(self.page)
        self.pushButton_imageHistogramSearch.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_imageHistogramSearch.setStyleSheet("color: rgb(120, 90, 80);\n"
"border-color: rgb(8, 8, 8);\n"
"border-style: outset;\n"
"background-color: rgb(245, 249, 237);\n"
"border-radius:15px;\n"
"border-width:1.5px;\n"
"font: bold italic 11pt \"MS Sans Serif\";")
        self.pushButton_imageHistogramSearch.setObjectName("pushButton_imageHistogramSearch")
        self.verticalLayout_4.addWidget(self.pushButton_imageHistogramSearch)
        self.pushButton_ = QtWidgets.QPushButton(self.page)
        self.pushButton_.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_.setStyleSheet("color: rgb(120, 90, 80);\n"
"border-color: rgb(8, 8, 8);\n"
"border-style: outset;\n"
"background-color: rgb(245, 249, 237);\n"
"border-radius:15px;\n"
"border-width:1.5px;\n"
"font: bold italic 11pt \"MS Sans Serif\";")
        self.pushButton_.setObjectName("pushButton_")
        self.verticalLayout_4.addWidget(self.pushButton_)
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_4.setStyleSheet("color: rgb(120, 90, 80);\n"
"border-color: rgb(8, 8, 8);\n"
"border-style: outset;\n"
"background-color: rgb(245, 249, 237);\n"
"border-radius:15px;\n"
"border-width:1.5px;\n"
"font: bold italic 11pt \"MS Sans Serif\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 765, 443))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.stackedWidget_2.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setStyleSheet("color: rgb(120, 90, 80);\n"
"background-color: rgb(245, 249, 237);\n"
"font: bold 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(8, 8, 8);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_8.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_3.setStyleSheet("color: rgb(120, 90, 80);\n"
"background-color: rgb(245, 249, 237);\n"
"font: bold 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(8, 8, 8);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem6)
        self.label__showImage_3 = QtWidgets.QLabel(self.page_4)
        self.label__showImage_3.setMinimumSize(QtCore.QSize(500, 350))
        self.label__showImage_3.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.label__showImage_3.setText("")
        self.label__showImage_3.setScaledContents(True)
        self.label__showImage_3.setObjectName("label__showImage_3")
        self.verticalLayout_9.addWidget(self.label__showImage_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_7.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(78, 177, 61);\n"
"font: bold 20pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(70, 255, 70);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_10.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(195, 70, 33);\n"
"font: bold 20pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color:rgb(255, 43, 43);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_10.addWidget(self.pushButton_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.label_imageMessage = QtWidgets.QLabel(self.page_4)
        self.label_imageMessage.setMinimumSize(QtCore.QSize(500, 100))
        self.label_imageMessage.setText("")
        self.label_imageMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imageMessage.setObjectName("label_imageMessage")
        self.verticalLayout_9.addWidget(self.label_imageMessage)
        self.gridLayout_4.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.label_4 = QtWidgets.QLabel(self.page_5)
        self.label_4.setStyleSheet("color: rgb(120, 90, 80);\n"
"background-color: rgb(245, 249, 237);\n"
"font: bold 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(8, 8, 8);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_9.addWidget(self.lineEdit_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_6.setStyleSheet("color: rgb(120, 90, 80);\n"
"background-color: rgb(245, 249, 237);\n"
"font: bold 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(8, 8, 8);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_9.addWidget(self.pushButton_6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.video_widget_2 = QVideoWidget(self.page_5)
        self.video_widget_2.setMinimumSize(QtCore.QSize(0, 400))
        self.video_widget_2.setObjectName("video_widget_2")
        self.verticalLayout_10.addWidget(self.video_widget_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.play_btn_2 = QtWidgets.QPushButton(self.page_5)
        self.play_btn_2.setMinimumSize(QtCore.QSize(75, 40))
        self.play_btn_2.setText("")
        self.play_btn_2.setObjectName("play_btn_2")
        self.horizontalLayout_11.addWidget(self.play_btn_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.page_5)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_11.addWidget(self.horizontalSlider_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.errorLabel_2 = QtWidgets.QLabel(self.page_5)
        self.errorLabel_2.setText("")
        self.errorLabel_2.setObjectName("errorLabel_2")
        self.verticalLayout_11.addWidget(self.errorLabel_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_9.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(78, 177, 61);\n"
"font: bold 20pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(70, 255, 70);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_12.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_10.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(197, 65, 25);\n"
"font: bold 20pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color:rgb(255, 64, 30);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_12.addWidget(self.pushButton_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.label_imageMessage_2 = QtWidgets.QLabel(self.page_5)
        self.label_imageMessage_2.setMinimumSize(QtCore.QSize(500, 100))
        self.label_imageMessage_2.setText("")
        self.label_imageMessage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imageMessage_2.setObjectName("label_imageMessage_2")
        self.verticalLayout_11.addWidget(self.label_imageMessage_2)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setStyleSheet("color: rgb(120, 90, 80);\n"
"background-color: rgb(245, 249, 237);\n"
"font: bold 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(8, 8, 8);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_2.setStyleSheet("color: rgb(120, 90, 80);\n"
"background-color: rgb(245, 249, 237);\n"
"font: bold 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width: 1.5px;\n"
"border-color: rgb(8, 8, 8);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.label__showImage_2 = QtWidgets.QLabel(self.page_3)
        self.label__showImage_2.setMaximumSize(QtCore.QSize(500, 300))
        self.label__showImage_2.setText("")
        self.label__showImage_2.setScaledContents(True)
        self.label__showImage_2.setObjectName("label__showImage_2")
        self.verticalLayout_8.addWidget(self.label__showImage_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.video_widget = QVideoWidget(self.page_3)
        self.video_widget.setMinimumSize(QtCore.QSize(0, 250))
        self.video_widget.setObjectName("video_widget")
        self.verticalLayout_7.addWidget(self.video_widget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.play_btn = QtWidgets.QPushButton(self.page_3)
        self.play_btn.setMinimumSize(QtCore.QSize(75, 40))
        self.play_btn.setText("")
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout_6.addWidget(self.play_btn)
        self.horizontalSlider = QtWidgets.QSlider(self.page_3)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_6.addWidget(self.horizontalSlider)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_imageHistogramSearch_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_imageHistogramSearch_2.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_imageHistogramSearch_2.setStyleSheet("color: rgb(120, 90, 80);\n"
"border-color: rgb(8, 8, 8);\n"
"border-style: outset;\n"
"background-color: rgb(245, 249, 237);\n"
"border-radius:15px;\n"
"border-width:1.5px;\n"
"font: bold italic 11pt \"MS Sans Serif\";")
        self.pushButton_imageHistogramSearch_2.setObjectName("pushButton_imageHistogramSearch_2")
        self.verticalLayout_6.addWidget(self.pushButton_imageHistogramSearch_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.errorLabel = QtWidgets.QLabel(self.page_3)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout_8.addWidget(self.errorLabel)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 765, 346))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.scrollArea_2)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.video_widget_3 = QVideoWidget(self.page_6)
        self.video_widget_3.setMinimumSize(QtCore.QSize(0, 600))
        self.video_widget_3.setObjectName("video_widget_3")
        self.verticalLayout_12.addWidget(self.video_widget_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.play_btn_3 = QtWidgets.QPushButton(self.page_6)
        self.play_btn_3.setMinimumSize(QtCore.QSize(75, 40))
        self.play_btn_3.setText("")
        self.play_btn_3.setObjectName("play_btn_3")
        self.horizontalLayout_13.addWidget(self.play_btn_3)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.page_6)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_13.addWidget(self.horizontalSlider_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.stackedWidget_2.addWidget(self.page_6)
        self.gridLayout_3.addWidget(self.stackedWidget_2, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_videoSearchP.setText(_translate("MainWindow", "Video Search"))
        self.pushButton_imageSearchP.setText(_translate("MainWindow", "Image Search"))
        self.pushButton_videoUploadP.setText(_translate("MainWindow", "Video Upload"))
        self.pushButton_imageUploadP.setText(_translate("MainWindow", "Image Upload"))
        self.label.setText(_translate("MainWindow", "Choose Image:"))
        self.pushButton.setText(_translate("MainWindow", " Browse "))
        self.pushButton_imageHistogramSearch.setText(_translate("MainWindow", "Search By Histogram"))
        self.pushButton_.setText(_translate("MainWindow", "Search By Mean Color"))
        self.pushButton_4.setText(_translate("MainWindow", "Search by Dominant Color"))
        self.label_3.setText(_translate("MainWindow", "Choose Image:"))
        self.pushButton_3.setText(_translate("MainWindow", " Browse "))
        self.pushButton_7.setText(_translate("MainWindow", "Upload"))
        self.pushButton_8.setText(_translate("MainWindow", "Cancel"))
        self.label_4.setText(_translate("MainWindow", "Choose Video:"))
        self.pushButton_6.setText(_translate("MainWindow", " Browse "))
        self.pushButton_9.setText(_translate("MainWindow", "Upload"))
        self.pushButton_10.setText(_translate("MainWindow", "Cancel"))
        self.label_2.setText(_translate("MainWindow", "Choose Video:"))
        self.pushButton_2.setText(_translate("MainWindow", " Browse "))
        self.pushButton_imageHistogramSearch_2.setText(_translate("MainWindow", "  Search   "))
from PyQt5.QtMultimediaWidgets import QVideoWidget
import images_rc
import multi_rc
